# -*- coding: utf-8 -*-
#
# Atizo - The Open Innovation Platform
# http://www.atizo.com/
#
# Copyright (c) 2008-2010 Atizo AG. All rights reserved.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#
from __future__ import unicode_literals
from djangojames.string import unaccented_map
from copy import copy
from django.utils.translation import ugettext_lazy as _

SELECTION_NAME = _('- Bitte wählen -')
NO_SELECTION = _('- Keine Auswahl -')

def sort_choice(choice, head_tuple=None):
    c = list(copy(choice))
    m = unaccented_map()
    c.sort(key=lambda x: unicode(x[1]).translate(m))
    if head_tuple:
        l = []
        l.extend(c)
        head = list(head_tuple)
        head.reverse()
        
        for k in head:
            l.insert(0,k)
        return l
    return c

def get_display(choice, key):
    for c in choice:
        if c[0] == key:
            return unicode(c[1])
    return ''
    
COUNTRY_CHOICES_HEAD = (
    ('ch1', _('Schweiz')),
    ('de1', _('Deutschland')),
    ('at1', _('Österreich')),
    ('fr1', _('Frankreich')),
)

COUNTRY_CHOICES = (
    ('ad', _('Andorra')),
    ('ae', _('Vereinigte Arabische Emirate')),
    ('af', _('Afghanistan')),
    ('ag', _('Antigua und Barbuda')),
    ('ai', _('Anguilla')),
    ('al', _('Albanien')),
    ('am', _('Armenien')),
    ('an', _('Niederländische Antillen')),
    ('ao', _('Angola')),
    ('aq', _('Antarktis')),
    ('ar', _('Argentinien')),
    ('as', _('Amerikanisch-Samoa')),
    ('at', _('Österreich')),
    ('au', _('Australien')),
    ('aw', _('Aruba')),
    ('ax', _('Ålandinseln')),
    ('az', _('Aserbaidschan')),
    ('ba', _('Bosnien-Herzegowina')),
    ('bb', _('Barbados')),
    ('bd', _('Bangladesch')),
    ('be', _('Belgien')),
    ('bf', _('Burkina Faso')),
    ('bg', _('Bulgarien')),
    ('bh', _('Bahrain')),
    ('bi', _('Burundi')),
    ('bj', _('Benin')),
    ('bm', _('Bermuda')),
    ('bn', _('Brunei')),
    ('bo', _('Bolivien')),
    ('br', _('Brasilien')),
    ('bs', _('Bahamas')),
    ('bt', _('Bhutan')),
    ('bv', _('Bouvetinsel')),
    ('bw', _('Botswana')),
    ('by', _('Weißrußland')),
    ('bz', _('Belize')),
    ('ca', _('Kanada')),
    ('cc', _('Kokosinseln')),
    ('cd', _('Die Demokratische Republik Kongo')),
    ('cf', _('Zentralafrikanische Republik')),
    ('cg', _('Kongo')),
    ('ch', _('Schweiz')),
    ('ci', _('Côte d\'Ivoire')),
    ('ck', _('Cook-Inseln')),
    ('cl', _('Chile')),
    ('cm', _('Kamerun')),
    ('cn', _('China')),
    ('co', _('Kolumbien')),
    ('cr', _('Costa Rica')),
    ('cu', _('Kuba')),
    ('cv', _('Kap Verde')),
    ('cx', _('Weihnachtsinsel')),
    ('cy', _('Zypern')),
    ('cz', _('Tschechische Republik')),
    ('de', _('Deutschland')),
    ('dj', _('Dschibuti')),
    ('dk', _('Dänemark')),
    ('dm', _('Dominika')),
    ('do', _('Dominikanische Republik')),
    ('dz', _('Algerien')),
    ('ec', _('Ecuador')),
    ('ee', _('Estland')),
    ('eg', _('Ägypten')),
    ('eh', _('Westsahara')),
    ('er', _('Eritrea')),
    ('es', _('Spanien')),
    ('et', _('Äthiopien')),
    ('fi', _('Finnland')),
    ('fj', _('Fidschi-Inseln')),
    ('fk', _('Falklandinseln (Malwinen)')),
    ('fm', _('Mikronesien')),
    ('fo', _('Faroer-Inseln')),
    ('ga', _('Gabun')),
    ('gb', _('Vereinigtes Königreich')),
    ('gd', _('Grenada')),
    ('ge', _('Georgien')),
    ('gf', _('Französisch Guyana')),
    ('gg', _('Guernsey')),
    ('gh', _('Ghana')),
    ('gi', _('Gibraltar')),
    ('gl', _('Grönland')),
    ('gm', _('Gambia')),
    ('gn', _('Guinea')),
    ('gp', _('Guadeloupe')),
    ('gq', _('Äquatorial-Guinea')),
    ('gr', _('Griechenland')),
    ('gs', _('Südgeorgien und Südliche Sandwichinseln')),
    ('gt', _('Guatemala')),
    ('gu', _('Guam')),
    ('gw', _('Guinea-Bissau')),
    ('gy', _('Guyana')),
    ('hk', _('Hongkong')),
    ('hm', _('Heard und McDonald-Inseln')),
    ('hn', _('Honduras')),
    ('hr', _('Kroatien')),
    ('ht', _('Haiti')),
    ('hu', _('Ungarn')),
    ('id', _('Indonesien')),
    ('ie', _('Irland')),
    ('il', _('Israel')),
    ('im', _('Isle of Man')),
    ('in', _('Indien')),
    ('io', _('Britisches Territorium im Indischen Ozean')),
    ('iq', _('Irak')),
    ('ir', _('Iran (Islamische Republik )')),
    ('is', _('Island')),
    ('it', _('Italien')),
    ('je', _('Jersey')),
    ('jm', _('Jamaika')),
    ('jo', _('Jordanien')),
    ('jp', _('Japan')),
    ('ke', _('Kenia')),
    ('kg', _('Kirgistan')),
    ('kh', _('Kambodscha')),
    ('ki', _('Kiribati')),
    ('km', _('Komoren')),
    ('kn', _('Saint Christopher/Kitts')),
    ('kp', _('Nordkorea')),
    ('kr', _('Südkorea')),
    ('kw', _('Kuwait')),
    ('ky', _('Cayman-Inseln')),
    ('kz', _('Kasachstan')),
    ('la', _('Laos')),
    ('lb', _('Libanon')),
    ('lc', _('Karibische Inseln - Saint Lucia')),
    ('li', _('Liechtenstein')),
    ('lk', _('Sri Lanka')),
    ('lr', _('Liberia')),
    ('ls', _('Lesotho')),
    ('lt', _('Litauen')),
    ('lu', _('Luxemburg')),
    ('lv', _('Lettland')),
    ('ly', _('Libyen')),
    ('ma', _('Marokko')),
    ('mc', _('Monaco')),
    ('md', _('Moldawien')),
    ('me', _('Montenegro')),
    ('mg', _('Madagaskar')),
    ('mh', _('Marschall-Inseln')),
    ('mk', _('Mazedonien')),
    ('ml', _('Mali')),
    ('mm', _('Burma')),
    ('mn', _('Mongolei')),
    ('mo', _('Macao')),
    ('mp', _('Nördliche Marianen-Inseln')),
    ('mq', _('Martinique')),
    ('mr', _('Mauretanien')),
    ('ms', _('Montserrat')),
    ('mt', _('Malta')),
    ('mu', _('Mauritius')),
    ('mv', _('Malediven')),
    ('mw', _('Malawi')),
    ('mx', _('Mexiko')),
    ('my', _('Malaysia')),
    ('mz', _('Mosambik')),
    ('na', _('Namibia')),
    ('nc', _('Neu-Kaledonien')),
    ('ne', _('Niger')),
    ('nf', _('Norfolk-Inseln')),
    ('ng', _('Nigeria')),
    ('ni', _('Nicaragua')),
    ('nl', _('Niederlande')),
    ('no', _('Norwegen')),
    ('np', _('Nepal')),
    ('nr', _('Nauru')),
    ('nu', _('Niue-Inseln')),
    ('nz', _('Neuseeland')),
    ('om', _('Oman')),
    ('pa', _('Panama')),
    ('pe', _('Peru')),
    ('pf', _('Französisch Polynesien')),
    ('pg', _('Papua-Neuguinea')),
    ('ph', _('Philippinen')),
    ('pk', _('Pakistan')),
    ('pl', _('Polen')),
    ('pm', _('Saint Pierre et Miquelon')),
    ('pn', _('Pitcairn')),
    ('pr', _('Puerto Rico')),
    ('ps', _('Palästinensisches Gebiet, Besetztes')),
    ('pt', _('Portugal')),
    ('pw', _('Palau-Inseln')),
    ('py', _('Paraguay')),
    ('qa', _('Katar')),
    ('re', _('Reunion')),
    ('ro', _('Rumänien')),
    ('rs', _('Serbien')),
    ('ru', _('Russische Föderation')),
    ('rw', _('Ruanda')),
    ('sa', _('Saudiarabien')),
    ('sb', _('Salomonen')),
    ('sc', _('Seychellen')),
    ('sd', _('Sudan')),
    ('se', _('Schweden')),
    ('sg', _('Singapur')),
    ('sh', _('Sankt Helena')),
    ('si', _('Slowenien')),
    ('sj', _('Svalbard und Jan Mayen-Inseln')),
    ('sk', _('Slowakei')),
    ('sl', _('Sierra Leone')),
    ('sm', _('San Marino')),
    ('sn', _('Senegal')),
    ('so', _('Somalia')),
    ('sr', _('Surinam')),
    ('st', _('Sao Tome & Principe')),
    ('sv', _('El Salvador')),
    ('sy', _('Syrien')),
    ('sz', _('Swasiland')),
    ('tc', _('Turks- und Caicos Inseln')),
    ('td', _('Tschad')),
    ('tf', _('Französische Gebiete im südlichen Indischen Ozean')),
    ('tg', _('Togo')),
    ('th', _('Thailand')),
    ('tj', _('Tadschikistan')),
    ('tk', _('Tokelau')),
    ('tl', _('Ost-Timor')),
    ('tm', _('Turkmenistan')),
    ('tn', _('Tunesien')),
    ('to', _('Tonga')),
    ('tr', _('Türkei')),
    ('tt', _('Trinidad und Tobago')),
    ('tv', _('Tuvalu')),
    ('tw', _('Taiwan')),
    ('tz', _('Tansania')),
    ('ua', _('Ukraine')),
    ('ug', _('Uganda')),
    ('um', _('United States Minor Outlying Islands')),
    ('us', _('Vereinigte Staaten')),
    ('uy', _('Uruguay')),
    ('uz', _('Usbekistan')),
    ('va', _('Vatikanstadt')),
    ('vc', _('Saint Vincent u. Grenadien')),
    ('ve', _('Venezuela')),
    ('vg', _('Jungfern-Inseln (UK)')),
    ('vi', _('Jungfern-Inseln (USA)')),
    ('vn', _('Vietnam')),
    ('vu', _('Vanuatu')),
    ('wf', _('Wallis und Futuna')),
    ('ws', _('Samoa-Inseln')),
    ('ye', _('Jemen')),
    ('yt', _('Mayotte')),
    ('za', _('Südafrika')),
    ('zm', _('Zambia')),
    ('zw', _('Zimbabwe')),
)

LANGUAGE_CHOICES_HEAD = (
    ('fr', _('Französisch')),
    ('en', _('Englisch')),
    ('de', _('Deutsch')),
)

LANGUAGE_CHOICES = (
    ('', SELECTION_NAME),
    ('ar', _('Arabisch')),
    ('cs', _('Tschechisch')),
    ('da', _('Dänisch')),
    ('de', _('Deutsch')),
    ('el', _('Griechisch')),
    ('en', _('Englisch')),
    ('es', _('Spanisch')),
    ('fi', _('Finnisch')),
    ('fr', _('Französisch')),
    ('he', _('Hebräisch')),
    ('hu', _('Ungarisch')),
    ('it', _('Italienisch')),
    ('ja', _('Japanisch')),
    ('ko', _('Koreanisch')),
    ('nl', _('Niederländisch')),
    ('no', _('Norwegisch')),
    ('pl', _('Polnisch')),
    ('pt', _('Portugiesisch')),
    ('ro', _('Rumänisch')),
    ('ru', _('Russisch')),
    ('sv', _('Schwedisch')),
    ('tr', _('Türkisch')),
    ('zh', _('Chinesisch')),
)